# ----------------------------------------------------------------------------
#
# Package             : bz2file
# Source Repo         : https://github.com/nvawda/bz2file
# Travis Job Link     : https://travis-ci.com/github/asellappen/bz2file/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: focal
arch:
  - amd64
  - ppc64le

python:
  - 3.7
  - 3.8

sudo: required
install:
  - pip install pytest
 # - python setup.py install
  - pip install --no-deps -e .
script:
  - python -m pytest -v test_bz2file.py -- --ignore=BZ2FileTest.testWithoutThreading
  
